[general]
library_name = "libLaMEM"
output_file_path = "./lamem_library.jl"
module_name = "libLaMEM"
jll_pkg_name = "LaMEM_jll"

prologue_file_path = "./prologue.jl"
epilogue_file_path = "./epilogue.jl"

auto_mutability = true              # Create mutable structures:
auto_mutability_with_new = true     # Allow creating empty structs
use_julia_native_enum_type = true
auto_mutability_ignorelist = []
auto_mutability_includelist = []


is_local_header_only = true


printer_blacklist = [
#
# Defined in the prologue
#
# Remove types defined in const.jl
#
  "PetscErrorCode",
  "PetscBool",
  "PetscDataType",
#
# Remove types we define ourselves
#
  "PetscInt",
  "PetscScalar",
  "PetscReal",
  "PetscComplex",

]

export_symbol_prefixes = ["CX", "clang_"]

[codegen]
use_ccall_macro = false
#function_argument_conflict_symbols = ["__PETSC__"]

[codegen.macro]
macro_mode = "basic"

